@ .\x64\Release\xoroshiro2.exe
@ .\x64\Release\xoroshiro2.exe
@ .\x64\Release\xoroshiro2.exe
@ .\x64\Release\xoroshiro2.exe
@ .\x64\Release\xoroshiro2.exe
@ .\x64\Release\xoroshiro2.exe
@ .\x64\Release\xoroshiro2.exe
@ .\x64\Release\xoroshiro2.exe
@ .\x64\Release\xoroshiro2.exe
@ .\x64\Release\xoroshiro2.exe
